### PR TITLE
test for #216

### PR DESCRIPTION
**Pull request by C-Otto**

### CODE REVIEW

**Review by mceachen — COMMENTED** [review]
Did you mean to upload `offset0.jpg.xmp` and `offset1.jpg.xmp`? 

There are many tags to encode Timezone offsets, so I didn't know which one you'd seen not work. 

I guess it'd be more rigorous to iterate through all the timezone offset synonyms, both for .xmp and .jpg, and write values and then read back to validate round-trip functionality?

**Comment by C-Otto** [comment]
Yes, sorry, I forgot about those files. I updated the PR. If the behavior is different for the different tags/sources, then I believe it would help to have +00:00 roundtrip tests for all of them, yes.

**Comment by C-Otto** [comment]
By the way, I'm not sure if I need `UTC+0` or if `UTC` also would do. I think Immich only cares about the existence of `tz`.

**Comment by mceachen** [comment]
See https://github.com/photostructure/exiftool-vendored.js/issues/216#issuecomment-2397857149

**Pull request closed without merging**
